### ISSUE TITLE
Exercise List - Leading Icon

### ISSUE THREAD

**Issue by jfrys** [wger-project/flutter#303]
## Use case

The leading icon for the list of exercises should be changed, since they are all the same icon currently - it does not seem necessary to have a leading icon if they are all the same and do not correlate to each individual exercise.

<img width="337" alt="ex list" src="https://user-images.githubusercontent.com/93684643/204167035-1ed14953-4c0b-4285-9543-2dcd37e8c8b5.png">

## Proposal

If the leading icon is needed, I believe an image of the exercise itself, muscle trained, or equipment used to perform the exercise would make more sense in this leading spot.

**Comment by rolandgeider** [comment]
Hi! Those icons do take the exercise's image and display it, if available. We decided to put them front and center in the overview (even more so on the web application) so that if there are images missing users would be "pushed" a bit to contribute them.

![image](https://user-images.githubusercontent.com/2280729/204559905-8b1c05fc-f2eb-4a3d-a88e-1c70f2d4d54e.png)

BTW, currently it's only possible to add new exercises over the mobile app, contributing e.g. images to an existing exercise is only possible over the web app, but this will surely change in the future

I'm closing here to keep the issue list manageable

**Comment by rolandgeider** [comment]
(obviously, if the images of exercises with images are not being shown, that would be a bug)
