### ISSUE TITLE
remove info button which expands nutritional plan dashboard widgets

### ISSUE THREAD

**Issue by Dieterbe** [wger-project/flutter#615]
that button shows meals (but without their titles) and optionally their ingredients
and has a log button to log the meal. (it's the only widget to have action triggers hidden in an expandable view)
i recently added a dedicated "meal log" button directly on the widget, which has a more streamlined flow.

therefore, we can remove the info button expansion, which simplifies things and removes confusion, and makes it more consistent with other widgets

**Comment by Dieterbe** [comment]
also i have 2 more arguments for removing the info button and its related expansion widgets:
1) it's not really 'more info about the plan', it's only more info about the specific meals of the plan, so it's misleading
2) the way it displays information is inconsistent wrt other places we display similar information (the meal tiles). it doesn't show the meal name, for example.

**Comment by Denpeer** [comment]
@Dieterbe 
Are we talking about the button in the screenshot below? I'm asking because I do see the meal title in that widget.
<img width="215" alt="image" src="https://github.com/user-attachments/assets/74ed914a-856d-49ce-bfd8-145d7a55ce34">
Also being able to edit the meal and see the nutritional information is quite usefull.

**Comment by Dieterbe** [comment]
No, I believe what you are showing is on the nutritional plan page
I was referring to the nutritional plan dashboard widget, on the app homepage
